/* Generated By:JJTree: Do not edit this line. ASTMagicalSpeech.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMagicalSpeech extends SimpleNode {
  public ASTMagicalSpeech(int id) {
    super(id);
  }

  public ASTMagicalSpeech(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d27a3063e5777ec9a7bd0571a3d2a5bf (do not edit this line) */
