/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;
  /** RegularExpression Id. */
  int DETERMINER = 13;
  /** RegularExpression Id. */
  int NOUN = 14;
  /** RegularExpression Id. */
  int PRONOUN = 15;
  /** RegularExpression Id. */
  int ADJ = 16;
  /** RegularExpression Id. */
  int VERB = 17;
  /** RegularExpression Id. */
  int PREPOSITION = 18;
  /** RegularExpression Id. */
  int WORD = 19;
  /** RegularExpression Id. */
  int LETTER = 20;
  /** RegularExpression Id. */
  int PERIOD = 21;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int INSIDE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\"/*\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 10>",
    "<NUMBER>",
    "<DIGIT>",
    "<DETERMINER>",
    "<NOUN>",
    "<PRONOUN>",
    "<ADJ>",
    "<VERB>",
    "<PREPOSITION>",
    "<WORD>",
    "<LETTER>",
    "\".\"",
  };

}
