/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
public interface ParserTreeConstants
{
  public int JJTMAGICALSPEECH = 0;
  public int JJTSTATEMENT = 1;
  public int JJTNOUNPHRASE = 2;
  public int JJTCOMPOUNDNOUN = 3;
  public int JJTPREPPHRASE = 4;
  public int JJTVERBPHRASE = 5;
  public int JJTNOUN = 6;
  public int JJTPRONOUN = 7;
  public int JJTDETERMINER = 8;
  public int JJTADJECTIVE = 9;
  public int JJTPREPOSITION = 10;
  public int JJTVERB = 11;


  public String[] jjtNodeName = {
    "MagicalSpeech",
    "Statement",
    "NounPhrase",
    "CompoundNoun",
    "PrepPhrase",
    "VerbPhrase",
    "Noun",
    "Pronoun",
    "Determiner",
    "Adjective",
    "Preposition",
    "Verb",
  };
}
/* JavaCC - OriginalChecksum=61d06ca3dd0517a828552756e7a83700 (do not edit this line) */
